### ISSUE TITLE
Suggestion: One-way associations

### ISSUE THREAD

**Issue by XDGFX** [tonarino/innernet#106]
I now have an Innernet network set-up and running, it looks great so far!

The use case is that we will have a large number of robots deployed at different physical locations. Each robot at the same physical location will be under the same CIDR, but robots at different physical locations are completely separate and do not need to communicate to each-other.

Admin devices are on a separate CIDR also.

I want to be able to connect to any of the deployed robots (e.g. through ssh). It seems the way I do this is creating an association, which works.

My main concern now, is that each robot now has a connection back to my computer. As there will be many robots deployed on networks out of our control, this feels like an unwanted security vulnerability.

I understand my computer's firewall should help, but it still feels wrong to have potentially hundreds of devices on unknown networks with the ability to connect back to my PC.

I *could* only connect to the Innernet network when I need to connect to a device, but that seems a little cumbersome.

Is there any way to allow connections **from** my admin device, **to** any of the deployment CIDRs and resultantly any robot, but block any uninvited connections **from** a robot **back** to the admin CIDR?

Sorry so much text, It's hard to condense what I'm trying to say ;)

**Comment by mcginty** [comment]
Hey @XDGFX!

> I now have an Innernet network set-up and running, it looks great so far!

Great to hear :)

> I understand my computer's firewall should help, but it still feels wrong to have potentially hundreds of devices on unknown networks with the ability to connect back to my PC.
> 
> Is there any way to allow connections **from** my admin device, **to** any of the deployment CIDRs and resultantly any robot, but block any uninvited connections **from** a robot **back** to the admin CIDR?

This is exactly what firewalls are for, in fact! Most firewalls are configured by default to allow only outgoing connections, and that's often enforce via IPv4 with NAT as well. For innernet, I recommend in your situation doing the same thing - ensuring that by default incoming connections are blocked (over at least your innernet interface, but it's typically good to have that as the default for all interfaces).

**Comment by XDGFX** [comment]
Hi! Thanks a lot for the reply. I understand, it does make sense. Thanks for the example as well, I'll look into it.

I personally still like the idea of some additional measures, maybe innernet could have a built-in firewall for it's own traffic, so it's not relying on the host's firewall to be set up properly, though I understand that this isn't a major issue.

**Comment by mcginty** [comment]
Totally agree - as things in the linux world settle on `nftables`, I can imagine innernet eventually making changes to the host firewall, or at least warning when it detects issues with the host firewall.

One of our main goals was to not "reinvent the wheel" with firewalls, so I'm still in the boat of trying to not write our own firewall code for now.
