### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by sydbarrett74** [tonarino/innernet#111]
On my FreeBSD 13 x86-64 server, I issued the following command:

`sudo cargo install --git https://github.com/tonarino/innernet --tag v1.4.0-beta.3 client`

The resulting errors occurred:

(previous lines omitted)
```

   Compiling ureq v2.1.1
error[E0425]: cannot find function `set_addr` in this scope
  --> shared/src/wg.rs:97:5
   |
97 |     set_addr(interface, address)?;
   |     ^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_up` in this scope
  --> shared/src/wg.rs:98:5
   |
98 |     set_up(
   |     ^^^^^^ not found in this scope

error[E0425]: cannot find function `add_route` in this scope
   --> shared/src/wg.rs:105:9
    |
105 |         add_route(interface, address)?;
    |         ^^^^^^^^^ not found in this scope

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `shared`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `client v1.4.0-beta.3 (https://github.com/tonarino/innernet?tag=v1.4.0-beta.3#d8513d3d)`, intermediate artifacts can be found at `/tmp/cargo-installraVkCg`

Caused by:
  build failed
```

Please advise.

**Comment by mcginty** [comment]
Hey @sydbarrett74! `innernet` doesn't have FreeBSD support right now (none of the maintainers use it, so we're looking for someone willing to take that on), so some methods like the one in your error only exist for either Linux or macOS. It probably won't be a ton of work to add FreeBSD work - especially if we start by just supporting the userspace client - it just hasn't been done yet.

**Comment by sydbarrett74** [comment]
I will definitely take this on when some bandwidth frees up. For now, I am going to close this bug, and when I start work, I'll just do a PR.
