### ISSUE TITLE
innernet-server@NETWORK.service fails on Fedora 34 server

### ISSUE THREAD

**Issue by harishpillay** [tonarino/innernet#119]
I've taken the innernet-server version for Fedora 33 and installed it on my Fedora 34. That probably is not a good idea, but short of me spinning up a Fedora 33, I thought I should file a issue as well.

I had to add in /usr/lib/systemd/system/innernet-server@.service an entry in the [Service] section:
StartLimitBurst=0

Then ran: "systemctl daemon-reload" and restarted the innernet-server daemon. It seemed to start but it failed shortly after and kept restarting and failing repeatedly.

The kernel on this Fedora 34 server is version:5.13.5.

I will spin up a F33 VM to see if this failure happens for the server code.

**Comment by mcginty** [comment]
Hey @harishpillay, please post some logs of the crash so I can be helpful.

**Comment by harishpillay** [comment]
I think I've figured out the issue. I had wg running on that server - my original setup with that host as the server and with 10 other peers. I've disabled that original setup (including systemctl disable wg-quick@wg0) and now systemd is not complaining. Next is to check if my peer is able to connect. 

Apologies for the false alarm :-).

**Comment by mcginty** [comment]
No worries, thanks for following up!

**Comment by harishpillay** [comment]
The innernet-server is running without complaints. A newly created peer, <peername>.toml is then "inn install <peername>.toml".

This system (client) was running generic wg which I've disabled (like what I did for the server).

I am getting this error on the install command:
✔ Interface name · <NETWORK NAME>
[*] bringing up the interface.
[*] Generating new keypair.
[*] Registering keypair with server (at 172.16.0.1:51820).
[E] failed to start the interface: http://172.16.0.1:51820/v1/user/redeem: Connection Failed: Connect error: No route to host (os error 113).
[*] bringing down the interface.
[E] Failed to redeem invite. Now's a good time to make sure the server is started and accessible!
[E] http://172.16.0.1:51820/v1/user/redeem: Connection Failed: Connect error: No route to host (os error 113)
===============

"ip a" does not list the interface and "netstat -nr" does not show the route to 172.16.0.0/16. 

On the server, on the other hand, "ip a" and "netstat -nr" do show the right info.

And, interestingly, from the peer, I CAN ping the server, ie ping 172.16.0.1.

I will reboot the client and test. Peer and server are running Fedora 34.

**Comment by harishpillay** [comment]
[root@gillman innernet]# ping 172.16.0.1
PING 172.16.0.1 (172.16.0.1) 56(84) bytes of data.
64 bytes from 172.16.0.1: icmp_seq=1 ttl=251 time=171 ms
64 bytes from 172.16.0.1: icmp_seq=2 ttl=251 time=4.79 ms
64 bytes from 172.16.0.1: icmp_seq=3 ttl=251 time=161 ms
64 bytes from 172.16.0.1: icmp_seq=4 ttl=251 time=4.82 ms
64 bytes from 172.16.0.1: icmp_seq=5 ttl=251 time=170 ms
64 bytes from 172.16.0.1: icmp_seq=6 ttl=251 time=4.99 ms
64 bytes from 172.16.0.1: icmp_seq=7 ttl=251 time=168 ms
64 bytes from 172.16.0.1: icmp_seq=8 ttl=251 time=5.05 ms
^C
--- 172.16.0.1 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7009ms
rtt min/avg/max/mdev = 4.787/86.136/171.078/81.274 ms

gillman is the peer.

**Comment by harishpillay** [comment]
Update on my previous comment. 

The 172.16.0.1 that I was reaching was NOT my server endpoint. But it was a system that was sitting at the ISP who I am connected to!! Amazing that non-routable IPs are routed into the ISP.

So, my client is NOT successfully establishing the link with the server.
