### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by vielmetti** [tonarino/innernet#12]
I have a couple of arm64 systems (Pi 400, Pi 4, and a server-class Ampere Altra) that I'd be interested in adding to an `innernet` network. If the project built binaries I'd test them, ditto with make targets.

**Comment by vielmetti** [comment]
First attempt to build with `cargo build` on the Pi 4 yields this error message:

```
error: failed to run custom build command for `clang-sys v1.1.1`
```

I installed clang with

```
apt-get install clang libclang-dev
```

and got past the clang-sys issue.

Next up is `socket2`, which says "Socket2 uses 1.46.0 as MSRV." Debian 10 provides Rust 1.41.1, so I need to update that.

**Comment by vielmetti** [comment]
Installed a fresh `rustc` and `cargo` using `rustup`, trying `cargo build` again. `socket2` is fine with "rustc 1.53.0-nightly (48691ea6e 2021-03-29)"

The build got pretty far, but error points to a platform issue:

```
   Compiling wgctrl-sys v1.0.0 (/home/emv/src/github.com/tonarino/innernet/wgctrl-sys)
error: failed to run custom build command for `wgctrl-sys v1.0.0 (/home/emv/src/github.com/tonarino/innernet/wgctrl-sys)`

Caused by:
  process didn't exit successfully: `/home/emv/src/github.com/tonarino/innernet/target/debug/build/wgctrl-sys-bdf69c9f9af8e474/build-script-build` (exit status: 101)
  --- stderr
  /usr/include/aarch64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found
  /usr/include/aarch64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', wgctrl-sys/build.rs:15:44
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vielmetti** [comment]
Did I install `clang`? Because when I installed it again the build went fine.

The docs could use some build instructions, specifically dependencies and minimum versions.

Everything builds! But it fails to link with

```
  = note: /usr/bin/ld: cannot find -lsqlite3
          collect2: error: ld returned 1 exit status
```

Install `sqliite3` and `libsqlite3-dev`, and with that everything builds! Now to test.

**Comment by bschwind** [comment]
Sorry for the trouble on this! I agree we should have build instructions and dependencies listed out. I'll try to address that today.

**Comment by Spindel** [comment]
I got it up and running on aarch64 with  the following steps:

on my host, x86_64 I had qemu-static installed (pre-req)

on host, as user:

`podman run -ti --rm -v $(pwd)/innernet:/build/innernet:rw,Z  --pull=always --platform linux/arm64 ubuntu:latest` 

in container:
```
apt update
apt-get -y install  clang curl libsqlite3-dev libclang-9-dev libclang1-9
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env
rustup update
cargo install cargo-strip
cd /build/innernet
cargo build --release --bins 
cargo strip
```

Qemu-static builds are a fair bit slower than cross-compiling on x86_64 => aarch64, but it was easier than figuring out which step in the chain was having issues with finding the correct C header file.

**Comment by mcginty** [comment]
Closing this issue as the problem wasn't arm64 support, but better build instructions which @bschwind has already added to the `README`.
