### ISSUE TITLE
AWS instance:  failed to start the interface

### ISSUE THREAD

**Issue by Tarmik0s** [tonarino/innernet#120]
Hi,

First of all this project is awesome! Now we are in the middle of implementing our VPN using innernet but we ran on issue an where our AWS instances cannot join the innernet's network . We're looking for a solution or even a recommendation is highly appreciated. Please see below commands:

> wget https://github.com/tonarino/innernet/releases/download/v1.4.0-beta.3/innernet_1.4.0.beta.3_amd64.deb
> sudo apt install ./innernet_1.4.0.beta.3_amd64.deb 
> sudo inn install ./aws1.toml

[!] /etc/innernet is world-accessible (mode is 0o755). This is probably not what you want.
✔ Interface name · innernet
[*] bringing up the interface.
[E] failed to start the interface: innernet - Operation not supported (os error 95).
[*] bringing down the interface.
[!] failed to bring down interface: innernet - Protocol not supported (os error 93).
[E] Failed to redeem invite. Now's a good time to make sure the server is started and accessible!

[E] innernet - Operation not supported (os error 95)

> cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"

Thanks!

**Comment by mcginty** [comment]
Hey @Tarmik0s! My first guess would be that something is wonky with your WireGuard situation on that OS, given the "Operation not supported" and "Protocol not supported" errors. What kernel are you on? Is WireGuard installed as a DKMS module, and if so is there something happening with you having Secure Boot enabled or something on your VM that might stop it from loading properly?

**Comment by Tarmik0s** [comment]
Hello @mcginty 

1.  What kernel are you on? 

 -  Linux 4.19.0-17-cloud-amd64
 
 2.  Is WireGuard installed as a DKMS module
 
 -  WireGuard was installed using apt 
 -  sudo apt-get install wireguard
 
 3.  Is there something happening with you having Secure Boot enabled or something on your VM that might stop it from loading properly?
 
 - I'm not entirely sure how to check it but I've checked syslog and journalctl but nothing is being thrown

**Comment by Tarmik0s** [comment]
Hi @mcginty,

It was working now, you are correct it has something to do with installation. I've re-installed the wireguard and add 'backport repository' Thanks!!
