### ISSUE TITLE
Accepting invites on macOS shows Linux instructions

### ISSUE THREAD

**Issue by bbqsrc** [tonarino/innernet#128]
```
    It's recommended to now keep the interface automatically refreshing via systemd:

        systemctl enable --now innernet@divvun
```

`systemctl` doesn't exist on macOS. Are there equivalent macOS instructions yet?

**Comment by brandonkal** [comment]
There is no systemd for macOS. The equivalent to run services is launchd which controllable with launchtl and plist files.
I wonder how you managed to build without it. Did the cli install a systemd unit file on your mac?

Homebrew has a neat wrapper around launchctl with brew services. Ultimately I wonder if it is possible to integrate this into the tap release for `brew services start innernet@divvun`

**Comment by mcginty** [comment]
Thanks for opening an issue about this! Yeah, that string is wrong on macOS. I think the easiest step would be to integrate with `brew services` and possibly also to have a launchd script generator.
