### ISSUE TITLE
Deleting a created network

### ISSUE THREAD

**Issue by thdxr** [tonarino/innernet#13]
Does innernet create any additional files besides the systemd ones? Want to cleanup some test networks I created and I didn't see a command for it

**Comment by bschwind** [comment]
An uninstall command is definitely something we want to add.

Aside from the systemd files, there is a database file located at `/var/lib/innernet-server/<interface>.db` and at `/etc/innernet-server/<interface>.conf`

I _think_ that's all of them but @mcginty will know for sure.

**Comment by mcginty** [comment]
Closed in https://github.com/tonarino/innernet/commit/a44fe0d3ad404655275dd54638eb046aea54404d
