### ISSUE TITLE
RFC 2526 // IPv6 overlay // inn install invite.toml fails on ipv6 forwarding enabled Linux hosts

### ISSUE THREAD

**Issue by afics** [tonarino/innernet#131]
Hi,

according to RFC 2526 [0] the first address i.e. "network address" of prefixes are used as anycast addresses. Innernet uses such an address for the "innernet-server" peer. This can not be changed (short of editing the database) as far as I am aware.

This behaviour is not RFC conform and poses problems on IPv6 forwarding enabled i.e. `net.ipv6.conf.all.forwarding=1` Linux hosts. Running `inn install invite.toml` on such a system fails as the innernet client can not communicate with the server over WireGuard:
```
# sysctl net.ipv6.conf.all.forwarding
net.ipv6.conf.all.forwarding = 1
# ip route get fd00:42::
anycast fd00:42:: from :: dev lo table local proto kernel src fd00:42:2601:: metric 0 pref medium
# sysctl -w net.ipv6.conf.all.forwarding=0
net.ipv6.conf.all.forwarding = 0
# ip route get fd00:42::
fd00:42:: from :: dev innernet0 proto kernel src fd00:42:2601:: metric 256 pref medium
```
As can be seen above traffic meant for the innernet-server peer is sent to the local host.

This can be fixed by disabling forwarding on the `innernet0` interface by running `sysctl -w net.ipv6.conf.innernet0.forwarding=0`. While this works I propose not doing it, since this would interfere with future (planned?) functionality like #22.

As I understand it the only real fix is not using the first address with all host bits set to zero for the innernet-server peer.

Regards,
Armin

[0] https://datatracker.ietf.org/doc/html/rfc2526

**Comment by mcginty** [comment]
Hey @afics, thanks so much for opening the issue. To avoid heavy migrations, I think the first step we can take it to set `innernet-server`'s IP to the second rather than the first address in the CIDR, and then add a warning if the internal network is IPv6 and IPv6 Forwarding is enabled about this bug.

**Comment by afics** [comment]
Hi @mcginty,

> I think the first step we can take it to set innernet-server's IP to the second rather than the first address in the CIDR,

Works for me, I think this is the right thing to do.

> add a warning if the internal network is IPv6 and IPv6 Forwarding is enabled about this bug.

Sounds good.

I assume migrating existing innernet networks is not possible by design, so I will just recreate my network once the patch is in. As you have already added a check in  [mcginty/ipnetwork](https://github.com/mcginty/ipnetwork/blob/3d6edbef1cf7ccbbb314a075ac771af39ff98609/src/ipv6.rs#L188), this will be in the next release?


Regards,
Armin

**Comment by mcginty** [comment]
@afics yep that's right, this will be in the next release.
