### ISSUE TITLE
Explain security rationale/implications for making IPs immutable

### ISSUE THREAD

**Issue by vlmutolo** [tonarino/innernet#139]
Innernet currently uses a model of an internal network that requires (pubkey, IP) pairs to be immutable and "pinned" such that, once a peer receives such a pair from the coordination server, it will never modify that pair. I.e., the coordination server cannot change the IP of a peer.

This model is fairly different from the standard model of network administrators being able to assign and reassign IP addresses at will. It's also somewhat in tension with the classical network operations concept of making subnets as small as possible, since if you're not reusing IPs, /24 IPv4 subnets start to seem small. 

I think it would be helpful to detail the specific reasons why innernet needs to assume immutable (key, IP) pairs, and that IPs can never be repurposed in a network. Some environments may not want to make the same security assumptions that innernet makes. 

The "introducing innernet" blog post lists one reason for this decision, which is that it limits the damage that a compromised coordination server can do to a network.

I also individually guessed that it may be helpful for server firewalls to do ACL by IP, and immutable IPs make that slightly easier. I'm not sure if that played a role in the decision to make the (key, IP) pairs immutable, however.

**Comment by amarao** [comment]
Just a comment: using ipv4 for innernet is a big сognitive inertia. There are no feasable reason to use IPv4 for innernet, as all connections are peer to peer, and innernet CAN allocate IPv6, and you don't need your network guys cooperation to have IPv6 inside wireguard.

Switching to IPv6 automatically remove any considerations for 'scarce ip'. Even modest /64 per user is more than enough for possible reallocations and renumerations.

P.S. I found that the best way is to allocate a /64 per peer. Basically, you manage only cidrs, and when you add a new user, you add a cidr for that user (/64). This allows user to have multiple devices, having keys replaced, OS reinstalled, etc. Just allocate user a new IP from his/her /64. No associations change required.

**Comment by mcginty** [comment]
You detailed the two main reasons accurately, @vlmutolo, and you're right that it diverges from the typical way IP subnetting works in the regular internet.

In this version of innernet, it felt like a more straightforward concept to tie an IP to an identity (making it simpler to pin pubkeys as well as define specific firewall rules by peer). That said, I can imagine a future version of the protocol that might not have the same strategy, as it can be quite limiting in other ways like implementing key rotation (currently, to rotate keys you need to create a new peer). The idea of having this "strong identity" type of addressing be an optional feature of innernet has also been floated in the past.

Liek @amarao said, using IPv6 internally can get rid of this sense of scarcity anxiety that IPv4 tends to cause, and doing things like per-peer CIDRs give you some nice benefits, too. Makes it seem worth considering switching to IPv6-only for internal addressing and giving peers a subnet to make this approach easier to emulate.

**Comment by vlmutolo** [comment]
Yeah, using IPv6 certainly seems like it solves most of the problems. Personally, I think it's a great solution. The point of opening this issue was more along the lines of "we should write down somewhere what the rationale is" than "this is a problematic system". I think it will work just fine to pin the (key, IP) pair.

I'm going to close this issue. Anyone searching for the rationale will hopefully find this. Maybe consider writing the two main reasons listed above in the README, or linking to this issue when it's mentioned that peers are immutable.

**Comment by mcginty** [comment]
Thanks @vlmutolo , that's a great idea. I appreciate you opening the issue to help with documenting all this. I'll try to add better text in the README.
