### ISSUE TITLE
connect to network from docker container?

### ISSUE THREAD

**Issue by justinrush** [tonarino/innernet#14]
I'd like to use this to replace some openvpn site-to-site madness but two of the sites only have servers that are kubernetes nodes. I can see some cool ways to run this - like having an innernet server in each k8s cluster, having a sidecar that does some sort of on-start-get-priv-key thing from the local innernet server to join the network. However, it appears the way the client tries to run is not permitted inside a docker image.

From a windows host:
Using ubuntu:20.04, I get this error when trying to add a network:
```
root@f513c653fc32:~# inn install invite.toml
✔ Interface name · test
[*] bringing up the interface.

[ERROR] Operation not permitted (os error 1)
```

From a linux host:
```
root@074863c023a2:~# inn install /mydocker.toml
✔ Interface name · test
[*] bringing up the interface.

[ERROR] No such file or directory (os error 2)
```

thoughts on if this could be possible?

**Comment by mcginty** [comment]
I'm wondering if this is related to https://github.com/tonarino/innernet/issues/5 - my understanding is that docker should work with WireGuard if the host's kernel has it.

Is it possible you just need to `modprobe wireguard`?

**Comment by justinrush** [comment]
> I'm wondering if this is related to #5 - my understanding is that docker should work with WireGuard if the host's kernel has it.
> 
> Is it possible you just need to `modprobe wireguard`?

I saw that one - I am above 5.6. I can reprovision the VM and try to manually modprobe if we think thats helpful.

I assume this means running docker on windows just won't work? not an issue for me, it was just how i was testing something, all my actual targets are linux.

**Comment by mcginty** [comment]
The more portable option is to use the wireguard-go userspace implementation instead of the kernel module, which works on Linux and should work in any docker container regardless of host modules.

**Comment by kamiller8118** [comment]
I dont know what any of that is our how to find it,  i am completely new to everything

**Comment by pilik88** [comment]
To tak jak ja, staram się zrozumieć cokolwiek...

[pilik88 - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=yz2a3)	[yz2a3]

On April 3, 2021 at 8:13 GMT, Kris ***@***.***> wrote:

I dont know what any of that is our how to find it, i am completely new to everything

**Comment by mcginty** [comment]
Check out the examples in #55 for details, this is now possible :).
