### ISSUE TITLE
[FEATURE REQUEST] ipv6 innernet-server support

### ISSUE THREAD

**Issue by pretentious7** [tonarino/innernet#15]
Hello! It would be great to have ipv6 support for the innernet-server.

**Comment by bmullan** [comment]
@pretentious7 
In the Blog post:
**https://blog.tonari.no/introducing-innernet**

It implies IPv6 is supported.

_In the Section Titled:  **Getting Started**_

> Our network CIDR is 10.42.0.0/16, giving us 64k IP addresses to play with! It can be much bigger than this of course, **_and it can be IPv6 as well._**

**Comment by pretentious7** [comment]
o, but when I try to put the ipv6 address of my server into the setup thing at the start of innernet-server it says invalid address?
```
? External endpoint () : 
```

**Comment by mcginty** [comment]
That's a bug alright! Thanks for the issue.

**Comment by mcginty** [comment]
This should be resolved in https://github.com/tonarino/innernet/pull/56 once it's merged.

**Comment by mk-fg** [comment]
Trying IPv6 setup with 1.3.0b1, it worked, but wasn't very obvious:

- `innernet-server new` gives "getting external IP address. failed to get external IP." messages when getting to "External endpoint" entry, even though global IPv6 is there.

- Prompt is just "External endpoint ·" - no default/example or format info, so not very obvious what to enter there.

- Entering just an `2a02:17d0:201:8b00:e745:5d31:5869:9845` address given something like "failed to parse address" error.

- Entering `[2a02:17d0:201:8b00:e745:5d31:5869:9845]` (another common IPv6 notation) fails to parse port instead - progress.

- Entering `[2a02:17d0:201:8b00:e745:5d31:5869:9845]:12345` works.

While "endpoint" kinda suggests that it should be host:port, there doesn't seem to be any examples in README or the blog post, and not in the prompt (if only IPv6 is assigned), so might cause some confusion and trial-and-error like steps above.

Best fix might be parsing IPv6 from the interface as an example, like it presumably works with IPv4, but maybe some fallback endpoint example (if that parsing fails) would help too.

Thanks!

**Comment by mcginty** [comment]
@mk-fg thanks so much for testing!

> * Prompt is just "External endpoint ·" - no default/example or format info, so not very obvious what to enter there.

It tries to resolve your external IP address and auto-fill that in, but it currently only does that for IPv4 addresses. I'll fix that to let it resolve either.


> While "endpoint" kinda suggests that it should be host:port, there doesn't seem to be any examples in README or the blog post, and not in the prompt (if only IPv6 is assigned), so might cause some confusion and trial-and-error like steps above.

Yeah, that is really confusing. I'll add explainer text to help make each prompt more clear.

> Best fix might be parsing IPv6 from the interface as an example, like it presumably works with IPv4, but maybe some fallback endpoint example (if that parsing fails) would help too.

That makes sense! That would be nice to have - I'd like to do that and at the same time maybe write a tiny dependency-less crate that can do the most simple possible DNS request to get a public IP address back, since the existing crates are very bloated. That way we don't have to rely on HTTP endpoints like `icanhazip.com`...

**Comment by mk-fg** [comment]
Moving past server init, there seem to be more breaking issues.

Creating invite from such IPv6 server, I get toml like this: 
```
[interface]
network-name = "test"
address = "10.42.1.1/16"
private-key = "..."

[server]
public-key = "..."
external-endpoint = "[2a02:17d0:201:8b00:e745:5d31:5869:9845]:12345"
internal-endpoint = "10.42.0.1:12346"
```

But then trying to redeem it on another host fails with timeout.

Looking at "wg" output during that process, it looks like that endpoint IPv6 gets completely zeroed-out somewhere:
```
peer: ...
  endpoint: [::]:12345
  allowed ips: 10.42.0.1/32
  transfer: 0 B received, 148 B sent
```

Running tcpdump confirms that it's not some bogus output from wg tools, and interface indeed is setup with peer IPv6 being all-zeroes:
```
22:54:31.622549 IP6 fe80::2090:1dff:fe9f:35bc.38380 > ::.12345: UDP, length 148
```

I'd guess that some weird bitwise manipulation in the code might cause this, as rust probably shouldn't have any kind of bad pointer issues, which often cause that kind of bug in C.

**Comment by mcginty** [comment]
Great catch @mk-fg, sorry for the hassle. This bug showed up when the `wgctrl-rs` code was refactored.

Interestingly, even removing the `unsafe { }` chunk, changing
```rust
unsafe { peer.addr6 }.sin6_addr.__in6_u.__u6_addr8 = s.ip().octets();
```
to
```
peer.addr6.sin6_addr.__in6_u.__u6_addr8 = s.ip().octets();
```

fixes the problem (although I like your code better).

Pushing a fix now, and will release a new beta.
