### ISSUE TITLE
Failed to start the interface with an ubuntu droplet

### ISSUE THREAD

**Issue by Tarmik0s** [tonarino/innernet#154]
Hi,

I just wanna ask for a recommendations on how to install innernet properly in a DO's droplet.  Before I'd encountered the same error with my ec2 instance and the fix is simply use the buster-backports packages instead of DKMS packages. Now I tried the same fix with my ubuntu droplet but I still can't bring up the virtual network interface.

Below is the error code:
[!] /etc/innernet is world-accessible (mode is 0o755). This is probably not what you want.
✔ Interface name · <>
[*] bringing up the interface.
[E] failed to start the interface: <> - Operation not supported (os error 95).
[*] bringing down the interface.
[!] failed to bring down interface: <> - Protocol not supported (os error 93).
[E] Failed to redeem invite. Now's a good time to make sure the server is started and accessible!

[E] <> - Operation not supported (os error 95)

> cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Thanks!

**Comment by mcginty** [comment]
Hey @Tarmik0s - does `modprobe wireguard` succeed for you if you run it on that droplet?
