### ISSUE TITLE
ZSH Completions not working

### ISSUE THREAD

**Issue by darthShadow** [tonarino/innernet#156]
https://github.com/tonarino/innernet/blob/9b1315b079c148daf8ae049255e1675d04c5303e/doc/innernet.completions.zsh#L326

The double-quotes surrounding the `"wg-quick down <interface>"` need to be replaced with single-quoted `'wg-quick down <interface>'` to get it working again.

**Comment by mcginty** [comment]
Thanks for the issue @darthShadow! Looks like we hit https://github.com/clap-rs/clap/issues/1596. I'll switch our `"` to `'`s.
