### ISSUE TITLE
override-endpoint doesn't always work

### ISSUE THREAD

**Issue by bensteinberg** [tonarino/innernet#159]
In one environment (Digital Ocean) I've been able to override endpoints to the peers' external IP addresses successfully; in another (AWS), the command appears to run fine, but the endpoints remain the instances' internal addresses. I've tried different combinations of fetching and restarting the connection, but no luck. Do you have any recommendations for either order of operations, or means for diagnosis?

I'm running 1.5.0 on all the peers/servers in question.

**Comment by bensteinberg** [comment]
When I run `inn -v fetch` locally I can see the endpoints getting updated to the correct (external) addresses, but then when I run `inn show` I see the internal addresses, and `inn list --tree` shows no connection to the peers in question.

**Comment by pzeinlinger** [comment]
I can confirm, that this problem happens with some nodes.

**Comment by bensteinberg** [comment]
And somewhat later, the Digital Ocean/multi-cable-modem network is fully connected. I'm guessing there's something I don't understand about timing and reconnection. I haven't examined the AWS/etc network yet.

**Comment by mcginty** [comment]
Huh, I'll try to reproduce this. Thanks for opening the issue.

**Comment by bensteinberg** [comment]
Thanks, @mcginty! I believe you fixed this in 991c643 -- peers using release 1.5.1 are correctly connected in both of my environments.
