### ISSUE TITLE
Report interface addresses only for defined interfaces

### ISSUE THREAD

**Issue by pzeinlinger** [tonarino/innernet#160]
Is it possible to select the interface addresses that are reported to the server?
I have multiple connections between nodes (k8s) with different addresses, but only one of them should be used to connect innernet nodes together.

**Comment by mcginty** [comment]
Hey @pzeinlinger, sorry I missed this. Are you referring to the interface addresses that are reported by the peers for NAT traversal?

**Comment by pzeinlinger** [comment]
Yes! :-)
Flannel creates a new interface which in turn has a private ip but must not be used by innernet.

**Comment by mcginty** [comment]
Hey @pzeinlinger, I just added more granular interface address reporting and exclusion to https://github.com/tonarino/innernet/commit/d7c491c8f309f1818d0faf598d6a4a96e2a4fce0, so you can specify CIDRs to ignore with `--exclude-nat-candidates 10.100.0.0/16`, for example, and it won't report local IPs within those ranges.
