### ISSUE TITLE
Reject invalid hostnames for network name in innernet-server new

### ISSUE THREAD

**Issue by pxeger** [tonarino/innernet#164]
When doing initial setup with `innernet-server new`, entering a network name that is not a valid hostname should result in an error. Currently it is accepted without complaint.

I ran in to this issue because I tried to use a name with an underscore in it (because I always forget that DNS names can't have underscores in them), but it could also apply to any other invalid character (e.g. non-ASCII).

```bash
$ sudo innernet-server new
? Network Name > my_invalid_name
...
```

When you try to configure the server (e.g. `innernet-server add-cidr`), an error message is presented, which is annoying because you must then go back and change the name.

```bash
$ sudo innernet-server add-cidr invalid_name
error: Invalid value for '<interface>': interface name is not a valid hostname
```

...but you can't delete a server using `innernet-server uninstall` because it also rejects invalid hostnames!

```bash
$ sudo innernet-server uninstall invalid_name
error: Invalid value for '<interface>': interface name is not a valid hostname
```

**Comment by mcginty** [comment]
Good catch! Sorry about that.
