### ISSUE TITLE
Innernet recycling IP's?

### ISSUE THREAD

**Issue by lonnietc** [tonarino/innernet#167]
Hello, 

I have been researching Nebula based projects for possible use in a highly scalable P2P project that will give the user a single simple way to join the P2P VPN Mech.

I think that your system is based up wireguard, but am not sure if it will allow a user (node) to join and dynamically get an IP for the node from the lighthouse public node?

Also, from what I read, when a node disconnects that that IP is not used again. Is this correct?

Thanks in advance.

**Comment by mcginty** [comment]
Hey @lonnietc!

IPs are allocated by the `innernet-server` (the "lighthouse" in our design) and are stable per peer for that private key's lifetime. Disconnects don't cause IP re-allocation.
