### ISSUE TITLE
TOML to conf ? 

### ISSUE THREAD

**Issue by f0unix** [tonarino/innernet#170]
I am extremely happy with this project. Although I want to be able to add configurations to Wireguard clients without the hastle of checking and matching toml to conf configuration files supported by Wireguard. 
Is there an easy way to do so ?
My purpose is to use Wireguard Android client and Wireguard Windows client with the TOML file generated by the innernet server

**Comment by mcginty** [comment]
Thanks! To clarify, is your request roughly the same as https://github.com/tonarino/innernet/issues/3: converting an innernet invitation into a vanilla WireGuard configuration that can be run by clients without the need for the `innernet` binary?
