### ISSUE TITLE
Configurable `SERVER_DATABASE_DIR` (or all directories in general)

### ISSUE THREAD

**Issue by ajgon** [tonarino/innernet#171]
I'm using `innernet-server` on OpenWRT, and it works great. However, by default, OpenWRT uses `tmpfs` for `/var` directory, and everything gets wiped out during restarts or upgrades. That includes innernet sqlite database.

Currently I'm using custom compilation, with paths altered, but is it possible, to make those directories configurable (for example via commandline flag)?

**Comment by mcginty** [comment]
Yes! I think there were a couple of other cases (there were a few folks that packaged it for the reMarkable OS as well, IIRC, that could use a config like this) that justify this.

Thanks for the reminder and for opening the issue.
