### ISSUE TITLE
Removal of the `inn` shortcut symlink/binary from OS packages

### ISSUE THREAD

**Issue by mcginty** [tonarino/innernet#176]
**We're going to be phasing out `inn` being packaged in favor of using normal shell aliases.**
Unfortunately, it's neither recommended nor often possible to auto-alias for your shells, so this change will require you to be the one to create the alias.

## fish
```fish
abbr -a inn innernet
```

## zsh
```bash
echo 'alias inn="innernet"' >> ~/.zshrc
```

## bash
```bash
echo 'alias inn="innernet"' >> ~/.bashrc
```

This will allow manpages and completions to work as expected, and is in general less of a hack than sometimes needing to include two copies of the same binary depending on the features of an OS's package manager.

Starting with version 1.5.2, there will be a warning printed when `inn` is called, and in the next version release the `inn` binary will be replaced by a stub that returns an error. After some time, the stub will be removed all together.

See https://github.com/tonarino/innernet/pull/175 for the original conversation and justifications.

**Comment by alerque** [comment]
I think this can be closed and probably un-pinned as well given the timeline and current state of things.

**Comment by strohel** [comment]
Oh yes, thanks for helping us keeping the issues clean, @alerque.
