### ISSUE TITLE
`wireguard-control`: kernel backend possibly not parsing large responses in `get_by_name()`

### ISSUE THREAD

**Issue by mcginty** [tonarino/innernet#187]
First reported in https://github.com/tonarino/innernet/issues/174#issuecomment-1009827346, we currently only pay attention to the first message returned in the generic netlink call to Wireguard when querying its state.

For interfaces with large numbers of peers such that a response needs to be split across multiple netlink messages, that may leave a lot of information out.

**Comment by mcginty** [comment]
@dancamarg0 this is released in [`v1.5.3-beta.2`](https://github.com/tonarino/innernet/releases/tag/v1.5.3-beta.2) if you want to try it out!

**Comment by dancamarg0** [comment]
hey @mcginty thanks for the quick response! I'm testing it right now and still see the same behavior when fetching peers.

Also I'm occasionally getting this error in the new version `[E] Network Error: timed out reading response`

**Comment by dancamarg0** [comment]
@mcginty we may be able to give you an innernet invite to a separate CIDR In our network for debugging, let me know if that's helpful and I'll try to sort this out.

**Comment by mcginty** [comment]
@dancamarg0 I was able to reproduce this locally and fixed it in [`v1.5.3-beta.3`](https://github.com/tonarino/innernet/releases/tag/v1.5.3-beta.3). For #188 I might take you up on that if I can't work it out soon :).
