### ISSUE TITLE
Serialized netlink packet larger than maximum size - Inn Server 

### ISSUE THREAD

**Issue by dancamarg0** [tonarino/innernet#188]
This is related to #174 .

We've been testing v1.5.3-beta2 in our nodes for 2 or 3 days now and so far it's looking good. Yesterday however I spotted the following error in our innernet-server (This is not happening in any of the client nodes)

```
Error: Serialized netlink packet (4104 bytes) larger than maximum size 4096
``` 

We deployed this new version on Jan 12th at around 7am UTC and spotted the first error at Jan 13th 14:53 UTC. We're adding new peers daily and I guess that's what made the netlink packets from the innernet-server to grow above maximum serialized size, though I'd expect this to grow exponentially as we add new peers if that was the case. FWIW it seems stuck at 4104 bytes.

See the full output in the file below
[innernet-server serve interface.txt](https://github.com/tonarino/innernet/files/7869597/innernet-server.serve.interface.txt)

**Comment by mcginty** [comment]
Thanks for the helpful debug info! Hopefully I've caught the culprit, and will be releasing a 4th beta shortly.
