### ISSUE TITLE
IPv6 NAT candidate reporting

### ISSUE THREAD

**Issue by Enter-tainer** [tonarino/innernet#191]
This is part of the output when I run `innernet show` on my device. These devices(arch, router, home-server) all have a ipv4 address (a private IP address, like 192.168.1.1), and a ipv6 address(a global unicast address). But it seems that only the ipv4 one is being used in innernet. If the ipv6 address can be used to connect peers, we can simply get rid of annoying NATs, and connect to peers directly through ipv6. 

So is it possible to use ipv6 addresses in innernet?

I've been using innernet for a while, it is really a great project! Many thanks for your great efforts.
```
 peer: arch (2t9yDWwyTY...)
    ip: 10.42.1.1
    endpoint: 192.168.147.80:60688
    last handshake: 19 minutes, 18 seconds ago
    transfer: 3.08 MiB received, 7.34 MiB sent
  peer: router (hLu6TevaY5...)
    ip: 10.42.1.3
    endpoint: 192.168.1.1:55552
    transfer: 0 B received, 1418.57 KiB sent
  peer: home-server (VhItncIvyG...)
    ip: 10.42.1.4
    endpoint: 192.168.1.7:33498
    last handshake: 1 minute, 43 seconds ago
    transfer: 36.27 KiB received, 133.89 KiB sent
```

**Comment by mcginty** [comment]
innernet can use IPv6 endpoints, and there are a couple reasons these endpoints aren't being used right now in your setup:

1) Your coordinating server is probably setup with an IPv4 endpoint, so clients are connecting to the server via IPv4 and the server is passing those addresses it sees to fellow peers. If the server were being reached over IPv6 it would be reporting other peers' IPv6 addresses.
2) Right now the innernet client is only reporting IPv4 addresses as NAT candidates, as it's a relatively new addition. This issue is a good reminder that it's time to add IPv6 addresses as other candidates though!

The quickest interim solution if your IPv6 addresses are not temporary would be to use `innernet override-endpoint` to manually specify an IPv6 endpoint that peers should use to connect.

**Comment by mcginty** [comment]
I went ahead and changed the title so that I can use it as the issue for adding IPv6 NAT candidates :). Thanks again for opening the issue!

**Comment by Enter-tainer** [comment]
I'm trying to implement this. I found that the client will collect its ip addresses, and then upload them to the server.
```rs
    let candidates: Vec<Endpoint> = get_local_addrs()?
        .filter(|ip| !nat.is_excluded(*ip))
        .map(|addr| SocketAddr::from((addr, device.listen_port.unwrap_or(51820))).into())
        .collect::<Vec<Endpoint>>();
```
I found that get_local_addrs() will only collect ipv4 addresses on my machine (archlinux, Linux 5.15.17-xanmod2-2 #1 SMP Fri, 28 Jan 2022 12:27:47 +0000 x86_64 GNU/Linux). 

code:
```rs
fn main() {
    let res: Vec<_> = get_local_addrs().unwrap().collect();
    dbg!(res);
}
```

output:
```
[client/src/main.rs:1170] res = [
    192.168.1.11,
]
```
my ip addresses
```
❯ ip -c a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq state DOWN group default qlen 1000
    link/ether b0:25:aa:3a:e8:2e brd ff:ff:ff:ff:ff:ff
    altname enp2s0
3: wlp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c8:b2:9b:a4:77:20 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.11/24 brd 192.168.1.255 scope global dynamic noprefixroute wlp1s0
       valid_lft 603722sec preferred_lft 603722sec
    inet6 2409:XXXX:XXXX:XXXX:XXXX:9bff:fea4:7720/128 scope global dynamic noprefixroute
       valid_lft 221625sec preferred_lft 135225sec
    inet6 2409:XXXX:XXXX:XXXX:XXXX:b877:583f:f3ab/64 scope global dynamic noprefixroute
       valid_lft 221624sec preferred_lft 135224sec
    inet6 fe80::3ba8:782e:19d5:bb3b/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
4: mgt: <POINTOPOINT,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group defaultqlen 1000
    link/none
    inet 10.42.1.1/16 scope global mgt
       valid_lft forever preferred_lft forever
```

After some test, I found that ipv6 addresses do not have a nla label. So I remove [this line](https://github.com/tonarino/innernet/blob/3055eb7a7864bc3b090b1becc3c54898c1050133/shared/src/netlink.rs#L162). And the output:

```
[client/src/main.rs:1170] res = [
    192.168.1.11,
    10.42.1.1,
    2409:XXXX:XXXX:XXXX:XXXX:9bff:fea4:7720,
    2409:XXXX:XXXX:XXXX:XXXX:b877:583f:f3ab,
]
```

Seems that now ipv6 addresses are collected, but innernet's address(10.42.1.1) is also collected.

I guess that it might be a bug when ipv6 addresses are not reported as cadidates (due to the experiement above). I'm glad to offer my help if needed. Thank you very much for your reply.

**Comment by Enter-tainer** [comment]
oh, there is already a pr implementing this. I will have a try on that branch.

**Comment by mcginty** [comment]
Oh great! Thanks for testing it!

I'll merge that and get another patch release out soon.

**Comment by mcginty** [comment]
Merged #192, closing. Thanks again for opening the issue.

**Comment by Enter-tainer** [comment]
Hi, I guess I'm facing mtu issues, when using 1.3.4-beta2. And this is possibly related to #102. I'm have a ipv4 CIDR range for innernet(10.42.0.0/16), and I'm connecting to a ipv6 peer. The mtu is set to 1420(by default). It seems that mtu is wrongly configured. When using iperf3, only the first few packages arrive to server. (See logs below)

```
❯ ip -c l
6: mgt: <POINTOPOINT,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/none
```

```
  peer: home-server (VhItncIvyG...)
    ip: 10.42.1.4
    endpoint: [2409:xxxx:xxxx:xxxx:xxxx:6bff:feef:1110]:33498
    last handshake: 1 minute, 11 seconds ago
    transfer: 375.96 KiB received, 9.54 MiB sent
```

```
❯ iperf3 -c home-server.mgt.wg
Connecting to host home-server.mgt.wg, port 5201
[  5] local 10.42.1.1 port 40428 connected to 10.42.1.4 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  76.1 KBytes   622 Kbits/sec    2   1.27 KBytes
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    1   1.27 KBytes
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0   1.27 KBytes
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    1   1.27 KBytes
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0   1.27 KBytes
^C[  5]   5.00-5.71   sec  0.00 Bytes  0.00 bits/sec    0   1.27 KBytes
```

After a I set mtu to 1350 for a while, that the network works. And the iperf3 tests give reasonable results.

```
❯ iperf3 -c home-server.mgt.wg
Connecting to host home-server.mgt.wg, port 5201
[  5] local 10.42.1.1 port 40432 connected to 10.42.1.4 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  3.53 MBytes  29.6 Mbits/sec    0    208 KBytes
[  5]   1.00-2.00   sec  1.98 MBytes  16.6 Mbits/sec    6    183 KBytes
[  5]   2.00-3.00   sec  2.48 MBytes  20.8 Mbits/sec    3    183 KBytes
```

I guess we need to handle this kind of situation: when connecting to ipv6 peers, but using a ipv4 CIDR range.

In previous tests, I only checked the  /var/lib/innernet/mgt.json, and I found that there is a ipv6 address in candidate list. Sorry for that!

**Comment by mcginty** [comment]
@Enter-tainer funnily enough I was just thinking about this right before you posted! Yes I think the MTU logic needs to be reworked. I think there are a couple routes here:

1. Set all innernet links to a "pretty safe" magic MTU of 1412, since peers can't be assumed to have an IPv4 or IPv6 endpoint.
2. Have innernet dynamically set the MTU to either 1412 or 1432 depending on if any peers have an IPv6 endpoint (less safe, since peer endpoints can change outside of the `innernet` binary setting them).
3. Do more complex discovery by looking at the routing table and identify the MTU of the interface over which wireguard traffic will be flowing, and calculate directly based on that for the maximum possible MTU.

I think for this upcoming release, I'm leaning option 1 to start with.

**Comment by Enter-tainer** [comment]
I did a `traceroute --mtu TARGET` test. I found that my mtu is actually 1410! That really surprise me. So I set the mtu to 1410-80 = 1330, then everything works. 

I'm testing the innernet connection using a wifi hotspot from my phone, and my phone uses 4G LTE, I guess the strange 1410 might result from 4G LTE. 

Maybe we should set mtu to the minimum mtu of ipv6: 1280, which cannot be safer. And I agree with you that the ultimate solution should be some mtu discovery techinques similar to `traceroute --mtu` . Thank you for your time!

**Comment by mcginty** [comment]
@Enter-tainer sorry for the lag in finishing this (I broke my leg and had to get surgery, lol). I think you're right that maybe it does make sense to set a lower MTU for the time being to guarantee connectivity, and then add PMTU functionality down the line (and the MTU is of course configurable via CLI arguments in the mean time).
