### ISSUE TITLE
Add parameters for noninteractive usage

### ISSUE THREAD

**Issue by aeber** [tonarino/innernet#20]
Hi!

Thank you so much for creating this tool, i really enjoy it thus far!

I'd like to suggest adding a feature to make this usable in some kind of automation. For that i think it would be really helpfull to be able to use innernet without answering to interactive prompts and use parameters instead.

Installation could then be done by calling something like
```
innernet install --iface kermpany --delete-invitation ./invitation.toml
```

Adding a peer:
```
innernet add-peer kermpany --cidr 10.42.128.0/17 --assign-ip 10.42.128.42 --name ryo --admin
``` 
and so on...

I've never written anything in rust up until yesterday but i might give it a shot if this is something you'd like to see in innernet.

**Comment by Spindel** [comment]
Agreed.  I tried to automate the setup of innernet to work with ansible, and got stuck on the fact that the server had to be used in interactive mode.

I would like to have a clear given paths and data  for parameters like name, and with the auto-guess behaviour for missing parameters.

Thus, it would be great if I do not have to manually assign ip-addresses, but can let the tooling set that up as it does in interactive mode, but have a clear "add node named humbug output to /var/lib/innernet-invites/humbug.toml" 

The goal, of course, is to automate installation and set-up of server, as well as of clients as much as possible.

**Comment by bschwind** [comment]
Sorry for the late reply, this is definitely a planned feature! We're using `structopt` already, so it shouldn't be particularly hard to add. Sorry it didn't make it into the first version!

@aeber we'll update this issue when it's added, or if you want to give it a try feel free to ask questions here on desired behavior or how to implement it in Rust.
