### ISSUE TITLE
Using the invitation file with native Wireguard clients

### ISSUE THREAD

**Issue by radupotop** [tonarino/innernet#200]
I've managed to take the settings from an invitation file and use them with a native Wireguard client (WG for Android). It's working fine for now but my gut feeling is that this is not the proper approach to take.

Please correct me if I'm wrong but from my understanding the invitation key is only meant to be used as a temporary step for onboarding new peers into the network. Once they are onboarded they get their permanent key from the innernet-server.  
The invitation key has an expiry date which makes it unfit for long-term use.

So what is the recommended approach in this case? Since I can't run innernet on Android.  
Should I set a very far expiry date for the invitation or set it to 0 maybe?

Thanks.

**Comment by alerque** [comment]
I'm not sure even your hack actually gets you on as a proper client in the network. It gets you connected to the orchestration server, but you then need to discover and add direct links and routes to all the other clients.

**Comment by radupotop** [comment]
Well yes it does. It only connects the Android client to the server but that's all I need.

I've taken one step further and made this hack permanent:

```
sqlite3 /var/lib/innernet-server/interface.db

update peers set invite_expires=NULL;
update peers set is_redeemed=1;
```

**Comment by alerque** [comment]
In a typical innernet setup the orchestration server is not even part of the regular network of peers. It is treated entirely differently and the expectation is that it is a box outside of your peer routings.

If all you need is to connect to the orchestration server why not just setup your own manually configured Wireguard interface on it and connect with an Android client as usual? I don't understand what you are accomplishing here if you aren't setting up links to any innernet peers.
