### ISSUE TITLE
Try using innernet for home network management

### ISSUE THREAD

**Issue by dnaka91** [tonarino/innernet#205]
Thanks for this awesome project. I tried setting it up, but ran into some issues along the way.

First, I feel this is a great way to manage several devices across different networks, but not sure whether my use case is appropriate for this tool. The docs and guides all mention more of a project setup with all devices being part of the same network group or so.

My plan was to set up the server on my VPS, then connect various devices from my own home and families' homes, so I can manage them easier and do quick troubleshooting when needed.

Set up the server on my VPS so far (Ubuntu 20.04, Linux kernel 5.4) with default settings and everything seems to run properly. Firewall is open on port `51820` as well. Then created 2 CIDRs for now, and tried to add peers, but that's where I got stuck. Copied the invite over from the server and tried to install it on my machine (macOS Monterey 12.3).

It seems that I can't reach the server properly, as I always get a `Connection Failed: Connect error: connection timed out.` error. Internal and external endpoints in the invite file both match the server IPs, so that seems good.

One thing that I figured what might be off is the Linux kernel version. I installed the `wireguard` package and the `innernet-server` runs successfully, but the readme mentions kernel **5.6** is required. Might that be an issue?

Do you have any idea how I could debug this to find the core issue?

**Comment by alerque** [comment]
Your user case is quite appropriate, that's one use case I use it for as well and it works great. I have one CIDR that is just some family computers spread out over several locations/continents/double nats/etc. and they are always reachable just a peer name away "host_name.cidr_name.wg".

I don't know about your kernel issue. My orchestration server is both publicly reachable and doesn't have any ports firewalled so anything innernet tries to open just works. I suspect you might need a range of ports open there, but somebody else may be able to speak to that better.

**Comment by dnaka91** [comment]
I figured out that is has something to do with the firewall on the server. My server is pretty locked down on the ports for security reasons. So it only accepts 80, 443 and a custom ssh port.

So I set up a temporary VPS and there it just works. As soon as I add firewall rules, I can't connect anymore.

Currently, I have only port `51820` enabled on both TCP and UDP, inbound and outbound, in addition to the above-mentioned ports. Are there any other ports that are needed by innernet or WireGuard to function properly?

**Comment by dnaka91** [comment]
It's odd, tried several times and in the end I uninstalled the whole network on client and server.

Then, after creating a new network... It just worked. No idea what the issue with the first network was, maybe some error that I missed or some step that I did wrong 🤷

Anyways it works now, so I'm gonna close this
