### ISSUE TITLE
Add --yes flag to innernet-server related commands for automation

### ISSUE THREAD

**Issue by jon77p** [tonarino/innernet#218]
In commit ddac328, the `--yes` flag was made available to the `innernet` client binary, however the same flaw were not added to the `innernet-server` binary. This prevents automations (such as using ansible to manage an innernet deployment) from being made possible on commands like "uninstall" on the internet server.

The logic added in the referenced commit seems to be straightforward enough that changes to the `innernet-server` binary should be easy, and I probably will look into making a PR if I implement the changes myself, but I also wanted to track this here for visibility!

**Comment by jon77p** [comment]
Thanks @mcginty for merging in PR #221! I'll mark this issue as resolved as it's been merged into main.

**Comment by mcginty** [comment]
Thanks for the PR! Sorry it took so long to merge.
