### ISSUE TITLE
[question, technical] Is peer-peer traffic routed through the server?

### ISSUE THREAD

**Issue by stheid** [tonarino/innernet#223]
After reading the [blog post](https://blog.tonari.no/introducing-innernet) i still don't understand how the protocol of innernet works on a technical level. Is innernet technically equivalent to [this implementation](https://github.com/jwhited/wgsd).

My main concern is: **Is all peer traffic piped through the rendezvous server**

[The accompanying blog](https://www.jordanwhited.com/posts/wireguard-endpoint-discovery-nat-traversal/#reviewing-the-communications-flow) has a lot nice visualizations. I was also wondering if innernet was inspired by that blog post.

**Comment by bschwind** [comment]
Hi @stheid, the rendezvous server does **not** relay traffic, peers talk directly to each other via their wireguard IP addresses. The server simply manages peer endpoints (and of course other logic related to CIDRs and peer management) so peers know where to direct their packets.

**Comment by stheid** [comment]
ah ok, than its very similar to Jordan Whited WGSD project. thanks for the clarification
