### ISSUE TITLE
Are there ARM builds planned

### ISSUE THREAD

**Issue by stheid** [tonarino/innernet#224]
Some closed issues (#50, #83) suggest, that its possible to cross-compile innernet for using it on a Raspberry Pi. I am wondering if its planned to add ARM packages into the CI pipeline.

**Comment by alerque** [comment]
Wouldn't your distro be the first place to approach for this? For example Arch Linux ARM has `innernet` packages already working out of the box for [armv7h](https://archlinuxarm.org/packages/armv7h/innernet) and [aarch64](https://archlinuxarm.org/packages/aarch64/innernet). It also looks like NixOS has ARM packages.

**Comment by stheid** [comment]
Oh i did not know that. thanks than i will have another look at which distros support Innernet for ARM and choose a OS that also supports my device. Thanks a lot.

I was not aware of that, because i somehow expected that there would be downloadable builds here at github if it where supported. Maybe it would than make sense to put a support list in the readme.
