### ISSUE TITLE
Allow deleting CIDR that has no peers

### ISSUE THREAD

**Issue by Eeems** [tonarino/innernet#23]
If you add a CIDR and realize that you made a mistake it would be good to allow removing the entry without having to edit the sqlite database.

**Comment by mcginty** [comment]
Makes sense

**Comment by mcginty** [comment]
For anyone experiencing this, if the CIDR has no children (neither peers nor other CIDRs), you can directly delete it in the SQLite database in the mean time (backing up the database before-hand is always encouraged of course).

We'll eventually add a CLI command to make this easier as well.

**Comment by Eeems** [comment]
> For anyone experiencing this, if the CIDR has no children (neither peers nor other CIDRs), you can directly delete it in the SQLite database in the mean time (backing up the database before-hand is always encouraged of course).

Yeah, that's what I ended up doing. Along with other edits >.>

**Comment by mcginty** [comment]
Yeah, we started with a pretty minimal set of operations, which can of course feel very rigid, but this also gives us flexibility to design the API better without as much cruft after seeing how people are using it :).

**Comment by Kerwood** [comment]
Oh yes please.. A delete CIDR would be great :)
