### ISSUE TITLE
Can't find debian packages

### ISSUE THREAD

**Issue by rehanog** [tonarino/innernet#236]
Apologies if I am missing something obvious.

From the README:
Fetch the appropriate .deb packages from https://github.com/tonarino/innernet/releases

I can't for the life of me find any packages on that releases page. Only see the sources

Help appreciated,

Many thanks

Rehan

**Comment by bschwind** [comment]
Related issue: #227

We need to get back in the habit of generating .deb files on each release, or perhaps removing that line from the README...

It's fairly simple to generate the debian files yourself, but let me know if you run into issues.

**Comment by strohel** [comment]
Hi @rehanog, sorry for incorrect info in readme. We've fixed that in https://github.com/tonarino/innernet/pull/238. Research on external build systems continues in https://github.com/tonarino/innernet/issues/203.
