### ISSUE TITLE
Connection timeout when redeeming invite; address not set in WG interface

### ISSUE THREAD

**Issue by agausmann** [tonarino/innernet#255]
As the title describes, when I try to install/redeem an invite on a client, it fails to connect to the HTTP server.

Output:

```
$ sudo innernet -vv install adventurer.toml
✔ Interface name · flock
[*] bringing up interface flock.
[D] set address fd67:263f:a76d:1::3/48 on interface flock
[D] set interface flock up with mtu 1280
[D] added route fd67:263f:a76d:1::3/48 to interface flock
[*] Generating new keypair.
[*] Registering keypair with server (at [fd67:263f:a76d::1]:51820).
[D] [ureq::stream] connecting to [fd67:263f:a76d::1]:51820 at [fd67:263f:a76d::1]:51820
[E] failed to start the interface: http://[fd67:263f:a76d::1]:51820/v1/user/redeem: Connection Failed: Connect error: connection timed out.
[*] bringing down the interface.
[D] [wireguard_control::backends::kernel] get_by_name: got 1 response message(s) from netlink request
[D] [wireguard_control::backends::kernel] get_by_name: parsed wireguard device flock with 1 peer(s)
[E] Failed to redeem invite. Now's a good time to make sure the server is started and accessible!

[E] http://[fd67:263f:a76d::1]:51820/v1/user/redeem: Connection Failed: Connect error: connection timed out
```

While waiting for the connection to time out, I checked the configuration of the `flock` interface and noticed it has no IP address: despite the "set address" log line above:

```
$ ip addr show flock
7: flock: <POINTOPOINT> mtu 1280 qdisc noqueue state DOWN group default qlen 1000
    link/none
```

This happens on 2 of my devices. I've tried kernel versions 6.3.1-zen2 and 6.1.28, and addresses `fd67:263f:a76d:1::1` through `fd67:263f:a76d:1::3` and nothing works.

However I have a third device that works fine, running kernel 6.1.28. I've tested it at addresses `fd67:263f:a76d:1::1` and `fd67:263f:a76d:1::2` and both work.

When the working device is connected, you can see the IP address with the same command:

```
$ ip addr show flock
18: flock: <POINTOPOINT,UP,LOWER_UP> mtu 1280 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet6 fd67:263f:a76d:1::2/48 scope global
       valid_lft forever preferred_lft forever
```

**Comment by agausmann** [comment]
If I run the install command, and then manually run these commands, I can successfully contact the server.

```
sudo ip link set flock up
sudo ip addr add fd67:263f:a76d:1::1/48 dev flock
sudo ip route add fd67:263f:a76d::/48 dev flock proto kernel
ping fd67:263f:a76d::1
```

**Comment by agausmann** [comment]
It seems to be a timing/synchronization issue with bringing up the interface, somewhere in here:

https://github.com/tonarino/innernet/blob/b4df350b1c9a956aa19ff4e3baf6ce41d8065f19/shared/src/wg.rs#L99-L106

If I add delays like this, then it succeeds (at least more reliably):

```rust
    std::thread::sleep(Duration::from_secs(1));
    set_addr(interface, address)?;
    std::thread::sleep(Duration::from_secs(1));
    set_up(interface, network.mtu.unwrap_or(1280))?;
    std::thread::sleep(Duration::from_secs(1));
```

**Comment by agausmann** [comment]
I'm not super familiar with WireGuard+Netlink, so I'm not sure how much deeper I can go.

**Comment by agausmann** [comment]
I checked the logs and noticed wpa_supplicant was attempting to access the wireguard interface. I stopped wpa_supplicant and innernet seems to work.

That makes sense, the devices that are having issues are all running wpa_supplicant, but the other device that worked fine does not have WiFi configured.

I guess I'll have to fix my wpa_supplicant configuration :sweat_smile:

**Comment by agausmann** [comment]
I'm going to close this since I've resolved my issue.

It may be worth adding this to the documentation or a troubleshooting guide, if other people might encounter this while running wpa_supplicant without specifying an interface.

**Comment by bschwind** [comment]
Sorry no one else commented but thank you @agausmann for documenting your steps along the way!

**Comment by agausmann** [comment]
To be precise, the problem is that I was running `wpa_supplicant` without the `-i` parameter, which specifies the interface it should control. Without that, it checks all network interfaces to find the Wi-Fi ones, and continuously checks for new ones, which interferes with innernet's control.

The fix is to specify that command-line parameter, for example `-i wlp5s0` . Then it will only control that interface and not check the others.
