### ISSUE TITLE
No 1.6.1 tag

### ISSUE THREAD

**Issue by jebotz** [tonarino/innernet#298]
There was a commit "meta: release v1.6.1" 3 weeks ago, but there is no such tag.  Thus the instruction for installation using Cargo, which say `cargo install --git https://github.com/tonarino/innernet --tag v1.6.1 server` fail.  Easy enough to just leave off the tag, for now, but still...

**Comment by alerque** [comment]
If this was actually intended as a release (which is seems like it might have been) it would definitely be nice to get it tagged so we can update distro packages as well.

**Comment by strohel** [comment]
Oh thanks for the notice @jebotz, @alerque, we indeed intended to cut the release in https://github.com/tonarino/innernet/pull/295, but forgot to push the tag.

I've pushed it right now and created the release on GitHub with notes: https://github.com/tonarino/innernet/releases/tag/v1.6.1

**Comment by alerque** [comment]
Updating on Arch Linux now...
