### ISSUE TITLE
Associations question

### ISSUE THREAD

**Issue by EranStockdale** [tonarino/innernet#325]
Hey there, just a quick question. With the associations, are they fully two-way? I'd quite like to be able to SSH into machines on, say, `work` from `home` but not be able to access `home` from `work` if possible.

**Comment by bschwind** [comment]
Hi @EranStockdale, yes the associations are fully two-way. What you described isn't currently supported, though I suppose you could come up with hacks to get around it by having an SSH forwarding server in between `home` and `work`.

**Comment by EranStockdale** [comment]
> Hi @EranStockdale, yes the associations are fully two-way. What you described isn't currently supported, though I suppose you could come up with hacks to get around it by having an SSH forwarding server in between `home` and `work`.

Ah alright, thanks!
