### ISSUE TITLE
Unsuccessful initial client register - leftover virtual interfaces

### ISSUE THREAD

**Issue by alesti** [tonarino/innernet#43]
Hi,

i am using v1.0.1 on server (linux) and on client side (mac, linux).
I couldnt register to the server in the first try while a made a mistake with the portforwarding on the server side and got an error:

```bash
[1] % sudo inn install ./aleks.toml
✔ Interface name testvpn
[*] bringing up the interface.
[*] Generating new keypair.
[*] Registering keypair with server (at 10.42.0.1:51821).

[ERROR] http://10.42.0.1:51821/v1/user/redeem: Connection Failed: Connect error: connection timed out
```

I checked, if the portforward to the internal server ip really works with netcat on both sides and it worked. 
I monitored the initial register try with tcpdump, but saw nothing on server side but `bad udp checksum` notes on client side.
Digging further around, i found a leftover virtual interface on the client system from a former try which used the same ip range and catched the connetion somehow.

I removed it (`sudo ip link delete <vpnname>`), and then it worked as expected and i could register my client.
Same same on mac, but it seems more difficult (or not possible?) to remove an utun type interface. i found it sufficient to take it down (`sudo ifconfig utunX down`).

It would be nice, if an unsuccessful register will remove all stuff which was setup by it.

Hey, innernet is reeeally promissing and looks great so far!
We missing some things (for example user management (decomission users, connection to ldap or oauth provider, ...) but this is v1, and it looks possible to adapt things with the api.

**Comment by mcginty** [comment]
Hey @alesti!

I just committed two related fixes to this:
1. a bug in macOS that would leave an interface hanging around on first run after reboot: https://github.com/tonarino/innernet/commit/dde58c8f45c9a0c2a14ef9422872e072ffa5d949.
2. Recovery code to remove half-initialized interfaces on a failed install at https://github.com/tonarino/innernet/commit/c15db6f83353d4befb85b0873a72df071d95ca99.

These changes are in https://github.com/tonarino/innernet/releases/tag/v1.1.0-rc.2, so should come out in v1.1.0 in the next day or two after testing 🙂.

**Comment by mcginty** [comment]
Closing this, released in https://github.com/tonarino/innernet/releases/tag/v1.1.0.
