### ISSUE TITLE
Cannot build client in Armbian 21.02 (arm64)

### ISSUE THREAD

**Issue by somini** [tonarino/innernet#44]
```
$ cargo build --release --bin innernet
   Compiling shared v1.0.1 (innernet-1.0.1/shared)
error[E0658]: use of unstable library feature 'bool_to_option'
   --> shared/src/prompts.rs:290:10
    |
290 |         .then(|| {
    |          ^^^^
    |
    = note: see issue #64260 <https://github.com/rust-lang/rust/issues/64260> for more information

error: aborting due to previous error
```

```
$  cargo --version; rustc --version
cargo 1.46.0
rustc 1.47.0
```

**Comment by bschwind** [comment]
`bool.then` was stabilized in Rust 1.50 according to the [docs](https://doc.rust-lang.org/std/primitive.bool.html#method.then)

Please feel free to re-open this issue if updating to rustc 1.50 or later doesn't solve the issue, though there is a separate discussion to be had about the minimum suported rust version.

**Comment by nikdoof** [comment]
Might be worth updating the README to indicate 1.50 as a minimum version, as it still specifies 1.46. Just hit the exact same issue.

**Comment by bschwind** [comment]
@nikdoof sorry about that! I updated the readme to specify 1.50.
