### ISSUE TITLE
`inn list --tree` should list cidrs in nummerical order

### ISSUE THREAD

**Issue by alesti** [tonarino/innernet#47]
Hi,

it would be nice and better to read if the order of listed cidrs in `inn list --tree` are in nummerical order, seems like today they are in the order of setup timestamp:

```
interface: fcloud (YOURMOM...)
  listening_port: 64180
  ip: 10.42.4.7
  10.42.0.0/16 fcloud
    10.42.0.1/32 innernet-server
    | 10.42.0.1 innernet-server
    10.42.4.0/22 humans
      10.42.4.0/25 fcloud-team
      | 10.42.4.1 aleks
      | 10.42.4.7 aleks-mac
      10.42.5.0/24 developers
      10.42.6.0/24 non-devs
    10.42.1.0/24 server
    | 10.42.1.1 teamspeak-srv
```    

This might be a problem on bigger setups. Or sort it alphabetical with the names (has other drawbacks).

Prio: low

I will add more of these, even if they are not important. 
I learned if i get used to new software i will accept a lot of little uncomfortable things as the right way to do it, even if they annoy new users. So it is better to note these little annoyances to track them for later fixing.

**Comment by mcginty** [comment]
This is great! Keep the issues coming :).
