### ISSUE TITLE
Add release notification webhook for Discord channel

### ISSUE THREAD

**Issue by Eeems** [tonarino/innernet#57]
![image](https://user-images.githubusercontent.com/1176979/115434354-d6d75e80-a1c5-11eb-8107-9244749ec42a.png)

You can reach me on Discord as Eeems#2244 for the webook if you'd like to set it up. If you'd rather not touch Discord yourself, just let me know what medium to get into contact with you on.

**Comment by ptman** [comment]
I tried to add a feed bot that follows https://github.com/tonarino/innernet/releases.atom . We'll see if it works when there's a new release

**Comment by Eeems** [comment]
It would probably work better to use webhooks and have GitHub push the message on a new release instead of having something poll a feed.

**Comment by mcginty** [comment]
Hey @Eeems, yeah I don't really use Discord regularly and I think I'd rather not get into the business of managing webhooks for unofficial channels - is that really the only way that Discord can get notifications for releases? That seems off from their side, no?

**Comment by Eeems** [comment]
I mean, it doesn't have to be unofficial. I could transfer ownership to you ;)

Webhooks isn't the only way, but I'd rather not run anything on my own servers to poll for and send notifications.

**Comment by ptman** [comment]
The RSS bot seems to do notifications just fine.

**Comment by mcginty** [comment]
Haha, unfortunately I don't think i would be a good steward for that community at the moment but I'm very happy to see it exist nonetheless!

If the RSS bot works well enough, I'd prefer that. If that doesn't work though, let me know and I can add a webhook for you 🙂

**Comment by mcginty** [comment]
I certainly appreciate you helping to build up a supportive community around innernet, I just want to be sure personally that I can manage all the things that I sign up for too. If you feel overwhelmed maintaining the community, remember that you have no obligation at all to do it forever (the mantra open-source maintainers must whisper to themselves at all times...).

I'll close this issue for now, and feel free to re-open if the RSS bot doesn't work out or anything else comes up!
