### ISSUE TITLE
Please don't edit /etc/hosts

### ISSUE THREAD

**Issue by bugaevc** [tonarino/innernet#6]
Thank you for this wonderful project, this sounds exactly like what I wanted (something like Tailscale, but without a proprietary server part, in Rust, using the in-kernel WireGuard module! 🎉)

There's one thing stopping me from adopting Innernet immediately: from the glance at the client source code, it appears that Innernet edits `/etc/hosts` in order to enable `.wg` names to work.

In my book, that's very wrong. `/etc/hosts` is the configuration written and maintained by me, the system administrator, not by any software.

Off the top of my head, the two better ways to add your hostnames to the system are:
* make a glibc NSS module (like nss-mymachines)
* run a special DNS server on the WireGuard interface; tell the rest of the system (i.e. with `resolvconf` or systemd-resolved API) to use it for the `wg` domain.

**Comment by ptman** [comment]
At least as an alternative

**Comment by mcginty** [comment]
First, thanks for your thanks! Second, yeah, you're absolutely right.

We felt dirty adding the /etc/hosts modification in the first place but the alternatives of trying to interface with the daunting wild west that is DNS configuration on linux felt very flimsy.

At the very least, innernet needs an option to not write to `/etc/hosts`, so that can be added right away.

In the long run, I'm interested in other cross-platform name resolution solutions that aren't prohibitively complicated (seems like we'd need to supporting vanilla resolv, resolvconf, systemd-resolved, *and* dnsmasq to get proper linux support).

What are the disadvantages to the NSS approach? Statically linked binaries and programs that don't use glibc wouldn't resolve names correctly. Are there other downsides?

**Comment by bugaevc** [comment]
I'm not exactly the most qualified person to answer this, but here are my thoughts.

* NSS is glibc-specific (though some other systems provide similar interfaces). This is not exactly *bad* (the users always appreciate when developers provide a specialized, native solution for a specific system!), but you'd still need to support a different solution for non-glibc systems. And yes, this won't work with software that skips glibc APIs and implements DNS clients itself.

   It may also be a bit non-trivial to make shared libraries — for one thing, you'd need to figure out how to build shared libraries for multiple architectures simultaneously with your buildsystem, and where to install them to (`/usr/lib/x86_64-linux-gnu/libnss_xxx.so` and `/usr/lib32/libnss_xxx.so` on my Debian box, `/usr/lib64/libnss_xxx.so` and `/usr/lib/libnss_xxx.so` on my Fedora box).

    It also means you need to configure NSS to add your NSS module for `hosts`. I'm not sure users will appreciate it if installing Innernet would automatically patch in `innernet` into their `/etc/nssswitch.conf` (or maybe they will, since apparently distro packages do this), or if you have to asks the user to enable it themselves. And please remember that on at least some systems, `/etc/nssswitch.conf` is actually managed by yet another configuration system (authconfig, authselect).

* An actual DNS server should be portable to other systems. The downside is the one you mention (there are *many* tools on different systems and setups that want to manage `resolv.conf`), and also always running yet another daemon in the background is suboptimal (although I guess it could be implemented inside the existing Innernet daemon). This also means having to actually implement DNS, which is quite a complex protocol with many tricky details (though you could make use of trust-dns-server).

**Comment by DanielJoyce** [comment]
I've used systems kinds like this and they usually created a synthetic network adaptor and populated routes. The central server then offered setting up dhcp configuration for hostnames and pushing that to the local client software that managed the virtual adaptors, etc

The use of cidrs to group things is a nice idea.  

What about bonjour/zeroconf as a possibility? Then boxes can announce themselves when available.

**Comment by Fastidious** [comment]
I am using Unbound right now to handle DNS for my WireGuard. Granted, it is not an automated process (if could be), but it allows for a central location to define hostnames, and all clients using that DNS “know" about each other.

**Comment by jedahan** [comment]
An option to choose the path of where to write the hosts entries may be a good middle ground that offers the ability to turn it off `--hosts-file /dev/null` and for resolvers that can be configured to read from multiple places or simply be part of scripts.

**Comment by bugaevc** [comment]
Unrealistic, but could also push everyone else to implement support for `/etc/hosts.d/` — then `/etc/hosts.d/innernet` would be OK 😀

**Comment by gmorenz** [comment]
Going to go against the grain slightly and vote for keeping /etc/hosts, at least as an option.

I don't want to be tied to glibc, nor do I want to add another moving part to all my systems for dns, nor is it the case that everything on the system is necessarily using the system dns resolver (especially in the age of DoH).

**Comment by bmullan** [comment]
@bugaevc @mcginty 

Just learned of **innernet** today.

To solve this problem could you utilize the open source tool for Wireguard called **[WGSD by Jordan Whitehed](https://www.jordanwhited.com/posts/wireguard-endpoint-discovery-nat-traversal/)**?   or... something similar?

_**[WireGuard Endpoint Discovery and NAT Traversal using DNS-SD](https://www.jordanwhited.com/posts/wireguard-endpoint-discovery-nat-traversal/)**_

> First, thanks for your thanks! Second, yeah, you're absolutely right.
> 
> We felt dirty adding the /etc/hosts modification in the first place but the alternatives of trying to interface with the daunting wild west that is DNS configuration on linux felt very flimsy.
> 
> At the very least, innernet needs an option to not write to `/etc/hosts`, so that can be added right away.
> 

Brian

**Comment by isavcic** [comment]
Some options could be:

- an API endpoint which generates a zone file, which can then be used in Unbound, BIND, CoreDNS, etc.
- an API endpoint which outputs JSON file containing the hostname-IP mappings

Both endpoints could, potentially, accept a parameter which would tell the API which CIDRs to output only, ie. if there's no association between CIDRs A and B, there's no need for their DNS resolvers to contain the information about the other CIDR.

**Comment by the-maldridge** [comment]
NSS is not a workable solution if you want to support all Linux distros, among other things it won't work on Alpine where NSS does not exist.  Ignoring this for the moment, NSS is a complex beast to wrestle with due to it loading into every process launched on the system.  In one of my own projects I've flagged NSS as out of scope because its semantics really aren't designed for interacting with the network in an online context (though I am working with the passwd/group/shadow databases, not the hosts database which could be completely cached to disk). 

I'd recommend adding an option to not edit the hosts file, but also adding an option to write everything that would have been written to the hosts file to somewhere else.  There are DNS servers that can [read this format directly](https://coredns.io/plugins/hosts/) and the format is trivial to parse with shell scripts to convert into bind9 style zone files or just about anything else you could want.

**Comment by jedahan** [comment]
`--write-hosts-to /any/path/youd/like` seems like it would address the issue for some cases.

**Comment by jrop** [comment]
And for those who do not want to write to any host file:

```
--write-hosts-to /dev/null
```

**Comment by mcginty** [comment]
I'm personally liking the proposed hosts path override solution (`--write-hosts-to <path>` and a convenience `--no-write-hosts`), it's simple and flexible (especially now knowing that modern DNS servers like CoreDNS can read the format).

While this can be added as a CLI flag in the mean time, are there any opinions on whether this is a machine-scoped (a new `/etc/innernet.conf`) vs. interface-scoped (`/etc/innernet/[interface].conf`) setting?

**Comment by the-maldridge** [comment]
DNS is usually a host level component, so it feels like this shouldn't be interface based.  That would be particularly strange to have some that are done that way and some that are interface scoped, but having them be logically split in the file, perhaps with comments of what interface/network they came from would be nice.

**Comment by kisik21** [comment]
On all of my machines running NixOS (the distribution is working on packaging innernet [here](https://github.com/NixOS/nixpkgs/pull/118007)) /etc/hosts is strictly read-only, so no option of changing /etc/hosts at all for me.
