### ISSUE TITLE
The innernet-server is not an eligible CIDR for peers

### ISSUE THREAD

**Issue by Kerwood** [tonarino/innernet#63]
The `innernet-server (10.42.0.1/32)` is not an eligible CIDR for creating peers in as its a `/32`.
Maybe remove it from the list ?

![innernet-server](https://user-images.githubusercontent.com/4029521/116814385-076daf80-ab59-11eb-8950-d7c2959f39d8.gif)

**Comment by mcginty** [comment]
Thanks for the issue. Yeah, makes sense to hide it since it's special in other ways anyway and it just gets in the way here.

**Comment by Kerwood** [comment]
@mcginty I realized i was using v1.0.0
The "/32" is still in the list, but the outcome is a little different. I have updated the GIF with the result from v1.2.0
