### ISSUE TITLE
Can't install .toml file when internal-endpoint is IPv6

### ISSUE THREAD

**Issue by bensteinberg** [tonarino/innernet#68]
I just set up a network with an IPv6 CIDR, some subnets inside it, and one peer. When I run `sudo inn install ./peer.toml` I get
```
[*] Registering keypair with server (at [fdxx:xxx:xxx::]:51820).
[*] bringing down the interface.
[!] Failed to redeem invite. Now's a good time to make sure the server is started and accessible!
```
but the `.toml` file has
```
external-endpoint = "12.34.56.78:51820"
```
Shouldn't `inn install` be using that address instead of the value of `internal-endpoint`?

**Comment by mcginty** [comment]
Hey @bensteinberg, sorry for the delayed response.

I just double-checked, and was able to make a network with an IPv6 internal CIDR, so I think that's not the problem. Perhaps the log message is confusing, but the address it's trying to talk to is correct - it brings the WireGuard interface up (with the only peer being the innernet-server whose endpoint should be correctly set to the `external-endpoint`), then communicates over the HTTP API via its internal address.

When trying to install and it's hanging, does WireGuard show that a handshake completed with the server peer? (`sudo wg`). This sounds more like a problem of a port not being forwarded, or the innernet-server not running (`innernet-server serve [network-name]`).

This is a good reminder to me to improve the error messaging to make this more straightforward to debug.

**Comment by bensteinberg** [comment]
Thanks, @mcginty! -- `systemctl status` showed that the innernet-server was running, but after a restart, adding the .toml file worked. I thought I'd tried a server restart already, but maybe not.

**Comment by mcginty** [comment]
Interesting - if there are any logs from the server that look out of place please feel free to open another issue if it could be a server bug!

**Comment by bensteinberg** [comment]
In the log right after I restarted the service, when I was able to install the peer, I see `INFO  innernet_server::api::user::handlers > WireGuard: adding new peer ... (...), removing old pubkey ...` -- the running server had a key from a previous experiment adding the peer. Does it make sense that the server would have required a restart to be able to remove the old one and add the new one?

**Comment by mcginty** [comment]
So the running server still had the temporary public key that was used in the invitation file you're saying? That would be a bug if so, the server should be removing that key (even though as long as the `AllowedIPs` changes to the new key, it's a benign issue).

**Comment by bensteinberg** [comment]
No, I thought the running server might have had a non-temporary public key from an earlier peer of the same name as the one I was trying to add, but now I'm not sure that makes sense.
