### ISSUE TITLE
allow for other routing methods

### ISSUE THREAD

**Issue by Johann150** [tonarino/innernet#70]
Currently innernet does static routing using the OS's built in tools in `shared/src/wg.rs`'s `add_route` function which is a good default functionality. However, if this functionality could be turned of somehow (not necessarily at runtime), that would enable users to choose other routing methods/protocols such as [babel](https://github.com/jech/babeld/).

Making innernet do that configuration would probably be a bit much, so by just switching this behaviour off (e.g. with a feature flag at compile time), people could configure their other routing methods themselves.

If this sounds like a reasonable idea, I can prepare a pull request on this.

**Comment by mcginty** [comment]
Interesting, never heard of babel before!

I'd gladly accept a pull request that adds CLI flags to disable routing table modifications.
