### ISSUE TITLE
Attempt to initialize innernet inside NAT'ed environment causes ENETUNREACH (os error 101)

### ISSUE THREAD

**Issue by amarao** [tonarino/innernet#73]
I've tried to start innernet on my local VM, which is under double NAT (my own machine is NATed, and VM on my host is NATed too).

Attempt to run innernet-server new fails with message `creation failed: Network is unreachable (os error 101).` (Which is `ENETUNREACH 101 Network is unreachable` according to `errno`).

Trace of the binary shows some odd interaction with cloudflare:
```
socket(AF_INET6, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_IP) = 6
bind(6, {sa_family=AF_INET6, sin6_port=htons(0), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::", &sin6_addr), sin6_scope_id=0}, 28) = 0
setsockopt(6, SOL_SOCKET, SO_RCVTIMEO_OLD, "\0\0\0\0\0\0\0\0 \241\7\0\0\0\0\0", 16) = 0
openat(AT_FDCWD, "/dev/urandom", O_RDONLY|O_CLOEXEC) = 7
read(7, "\310\320", 2)                  = 2
close(7)                                = 0
connect(6, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("1.1.1.1")}, 16) = 0
sendto(6, "\310\320\1\0\0\1\0\0\0\0\0\0\6whoami\ncloudflare\0\0"..., 35, MSG_NOSIGNAL, NULL, 0) = 35
socket(AF_INET6, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_IP) = 7
bind(7, {sa_family=AF_INET6, sin6_port=htons(0), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::", &sin6_addr), sin6_scope_id=0}, 28) = 0
setsockopt(7, SOL_SOCKET, SO_RCVTIMEO_OLD, "\0\0\0\0\0\0\0\0 \241\7\0\0\0\0\0", 16) = 0
openat(AT_FDCWD, "/dev/urandom", O_RDONLY|O_CLOEXEC) = 8
read(8, "\204e", 2)                     = 2
close(8)                                = 0
connect(7, {sa_family=AF_INET6, sin6_port=htons(53), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "2606:4700:4700::1111", &sin6_addr), sin6_scope_id=0}, 28) = -1 ENETUNREACH (Network is unreachable)
close(7)                                = 0
close(6)                                = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\33[31mcreation failed\33[0m: Networ"..., 65creation failed: Network is unreachable (os error 101).
) = 65
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
```

I think, demanding for a white IP in such odd way is very hard to debug. Shouldn't user be asked directly about such things?

Secondly, It looks like it can't be used on non-internet network. Why?

**Comment by mcginty** [comment]
Hey @amarao! Wow you're fast - I just added that code to try using DNS-based public IP resolution a few hours ago, it's only in pre-release versions of innernet. Thanks for testing them and for catching this. We shouldn't be crashing on this, I"ll fix that.

I switched from doing HTTP requests to `icanhazip.com` (who I have no idea who runs it) to using Cloudflare's `1.1.1.1` which felt more benign. I'd like to reach a happy middle-ground between convenience and privacy and am happy to add a consent check before pinging an external server, I just don't want to overload people with too many prompts. Are there other examples in the wild of the "right way" to do this?

**Comment by mcginty** [comment]
I went ahead and added a consent prompt before sending any external packets, and also stopped the failure of that query from killing the initialization wizard.

**Comment by amarao** [comment]
Thank you!
I think, there can be a bit more heuristics here.

1. If server has a 'white ip' on a single interface, and there is a default route pointing to this interface, it's safe to assume that it is the 'external IP'. This is a very common server configuration (excluding most clouds, unfortunately).
2. If there is no 'white ip', or there is no default gateway, or there are few addresses, etc ('odd configuration'), than some kind of autodetection may be welcomed with a prompt and a fallback.

**Comment by mcginty** [comment]
I'm not sure what 'white ip' means in this context - I'm assuming you mean global-scoped or externally reachable?

Thanks for the suggestions - we can look into adding some more magic logic to try to auto-fill external IPs without the need for third parties in the future.

**Comment by amarao** [comment]
'white IP' is a handy name for globally routable unicast addresses.  For both IPv4 and IPv6 they are well-known, and if there is a default route, it's 99% chance that this address is on a server with externally accessible (may be, through firewall), routable IP.

IANA database for allocated addresses: https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.xhtml
Basically, everything in LEGACY/ALLOCATED is routable. Reserved ranges are not.

For IPv6: https://www.iana.org/assignments/ipv6-address-space/ipv6-address-space.xhtml it's even simpler: `2000::/3` is global unicast.
