### ISSUE TITLE
Why is the server not listening on a public interface

### ISSUE THREAD

**Issue by jakubgs** [tonarino/innernet#81]
I'm playing with Innernet, and I don't get how the `innernet-server` service is supposed to be accessible from outside.

I've created a network:
```
 # innernet-server new        
[!] updated permissions for /etc/innernet-server to 0700.
[!] updated permissions for /var/lib/innernet-server to 0700.
Here you'll specify the network CIDR, which will encompass the entire network.
✔ Network CIDR · 10.42.0.0/16
getting external IP address.
✔ External endpoint · 12.34.56.78:51820
✔ Listen port · 51820
[*] Created database at /var/lib/innernet-server/example.db
```
And I enabled the service:
```
 # systemctl enable --now innernet-server@example 
Created symlink /etc/systemd/system/multi-user.target.wants/innernet-server@example.service → /usr/lib/systemd/system/innernet-server@.service.
```
And it seems to run fine:
```
 # journalctl -o cat -n 4 -u innernet-server@example 
INFO  innernet_server > bringing up interface.
INFO  innernet_server::endpoints > spawning endpoint watch thread.
INFO  innernet_server            > 1 peers added to wireguard interface.
INFO  innernet_server            > innernet-server 1.2.0 starting.
```
But it's only listening on the virtual wireguard port on `51820` port:
```
 # netstat -lpnt | grep innernet
tcp        0      0 10.42.0.1:51820         0.0.0.0:*               LISTEN      1756680/innernet-se
```
Which results in invites not being usable:
```
[*] Registering keypair with server (at 10.42.0.1:51820).
[*] bringing down the interface.
[!] Failed to redeem invite. Now's a good time to make sure the server is started and accessible!

[ERROR] http://10.42.0.1:51820/v1/user/redeem: Connection Failed: Connect error: connection timed out
```
What am I doing wrong? I'm running `1.2.0` on Ubuntu 20.04.2.

**Comment by mcginty** [comment]
Hey @jakubgs - is your server exposing `51820/udp` to the public? That port needs to be open to establish the WireGuard connection before the HTTP request can succeed.

**Comment by jakubgs** [comment]
Oh, you're absolutely right, my issue was that I didn't open UDP port on the cloud provider firewall, just on the host. Thanks!

**Comment by mcginty** [comment]
No worries - I will work on adding better diagnostics (checking if the WireGuard handshake succeeded to help people work out whether it's the WireGuard connection or the HTTP server that's the issue).

**Comment by mannp** [comment]
Hi @mcginty I appreciate the op got it sorted but I admit I am having the same issue.

I have installed server on my arch linux box and am trying to get to it from another device on my lan, with no joy.

Why would I need to open ports on my fw while using on a local lan?

I am still having the issue of the peer not being able to connect and so cannot be added.

**Comment by mcginty** [comment]
Hey @mannp, you'd need to give more details of your setup for me to be helpful here, but firewalls can and certainly do block traffic from local LAN IPs often times, so I wouldn't rule that out as being the issue unless you're confident it's configured to allow all local traffic.

**Comment by mannp** [comment]
> Hey @mannp, you'd need to give more details of your setup for me to be helpful here, but firewalls can and certainly do block traffic from local LAN IPs often times, so I wouldn't rule that out as being the issue unless you're confident it's configured to allow all local traffic.

Hi @mcginty thanks for coming back to me :) 

I have tried the default server setup on an arch linux box and then tried to add another machine, that failed as it couldn't find the server, although that is on a different vlan which made sense, but then I tried to add the same machine as a client that I am running the server on and that failed too :-/

I will read through the docs again to see what i am missing :)

**Comment by waynr** [comment]
@mcginty I'm having similar difficulty here:
```
root@meow:~# lsof -i -n -P | grep innernet
innernet- 43525            root    7u  IPv4 372760      0t0  TCP 172.29.0.1:51234 (LISTEN)
```
Here `172.29.0.1` is supposed to be the internal IP of my `inneret-server` instance:
```
root@waynr:~# cat /etc/innernet-server/wg25.conf
private-key = "meow"
listen-port = 51234
address = "172.29.0.1"
network-cidr-prefix = 16
```

Should that `address` value be something other than the server's internal/vpn network IP? That seems to be where the TCP listener gets its address from:
https://github.com/tonarino/innernet/blob/a9e2f55c91d1fb6fc58add79c3c26125a1fd4a2c/server/src/main.rs#L629

It's not clear to me from looking at the source code how it would ever listen on any other address :thinking:

**Comment by waynr** [comment]
Ah, is this supposed to bind it to all addresses on the interface? https://github.com/tonarino/innernet/blob/a9e2f55c91d1fb6fc58add79c3c26125a1fd4a2c/server/src/main.rs#L660

I do see my public ip address on the wg25 interface:
```
15: wg25: <POINTOPOINT,UP,LOWER_UP> mtu 1280 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 172.29.0.1/16 scope global wg25
       valid_lft forever preferred_lft forever
    inet my.public.ip.address/16 scope global wg25
       valid_lft forever preferred_lft forever
```

**Comment by waynr** [comment]
Okay coming back to this a bit later, I think it shouldn't be necessary for the server to listen on the external endpoint -- the external endpoint is only used for the initial invite-redeeming wireguard connection. Once that connection is up, the internal endpoint from the invite config is used to talk to the innernet server so that client-generated peer info (public key and peer address, i think) can be updated in the server's database.

For me the lack of public ip binding on the server side was just a red herring. My actual problem:

```
[E] failed to start the interface: wg25 - Operation not supported (os error 95).
```

So some kind of wireguard interface bringup operation is failing on the client side. I should be able to figure this out. Sorry for the ping!
