### ISSUE TITLE
access to peers on LAN

### ISSUE THREAD

**Issue by bensteinberg** [tonarino/innernet#93]
One use case I thought of for innernet to is to serve an application running on one machine inside a LAN via reverse proxy on another machine on the same LAN -- so even if the application is not protected by a cert, the traffic between it and the reverse proxy is encrypted. However, I find that innernet peers can't reach each other when they're inside a LAN together. I thought that `override-endpoint` might be the answer, but I haven't been able to figure it out. I've also considered running an `innernet-server` inside the LAN, for this purpose only, but haven't tried it yet. Am I barking up a wrong tree? Thanks!

**Comment by mcginty** [comment]
Hey @bensteinberg! Yeah, you've run into an issue of innernet not having an [ICE-esque](https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment) functionality that would allow peers to try connecting to multiple IPs along the "NAT pipeline" of any given connection.

You're right that `override-endpoint` should do the trick though, assuming you don't need to ever connect via a public IP.

Another option to investigate depending on your NAT situation is to simply enable what's called [hairpinning](https://en.wikipedia.org/wiki/Hairpinning), or NAT loopback. This is often not on by default, and unfortunately is sometimes not an option to enable depending on your hardware.

**Comment by bensteinberg** [comment]
Thanks, @mcginty. It looks like hairpinning is the right answer -- my current router doesn't do it, but the new one sitting on my desk does, and this is a nice incentive to configure and start using it.

Thanks again, and thanks so much for this project. I'm a huge fan -- I'm using innernet at work and at home now.
