### ISSUE TITLE
No such file or directory (Mac OS Big Sur/M1)

### ISSUE THREAD

**Issue by linuskendall** [tonarino/innernet#95]
I can't seem to set up innernet on a Mac OS host. It works fine on all Linux setups, but on Mac OS I'm getting no such file or directory (can't create the utun3 interface?).

```
[*] bringing up the interface.
[D] [shared::wg] ifconfig utun3 inet 10.42.64.1/15 10.42.64.1 alias
[D] [shared::wg] status code Some(0)
[D] [shared::wg] ifconfig utun3 mtu 1420
[D] [shared::wg] status code Some(0)
[D] [shared::wg] route -n add -inet 10.42.64.1/15 -interface utun3
[D] [shared::wg] status code Some(0)
[E] failed to start the interface: No such file or directory (os error 2).
```

Wireguard-go installed via brew.

**Comment by mcginty** [comment]
Fixed! Pushing out v1.3.1 now. Sorry for the bother.

(With v1.3.0 all you have to do is just run the command one more time and it will succeed the second time.)

**Comment by linuskendall** [comment]
Thanks for the quick fix!

I did try to run it a few times, but no luck. I'll test 1.3.1 now.

**Comment by mcginty** [comment]
Gotcha, it might have failed at another step. Please feel free to re-open if 1.3.1 didn't fix this.

**Comment by linuskendall** [comment]
Nailed it. Thanks a bunch. Works fine now.
