### ISSUE TITLE
wgctl-{sys,rs} crates

### ISSUE THREAD

**Issue by kbknapp** [tonarino/innernet#97]
Are there plans to put the `wgctl` crates on crates.io? They appear to be genuinely useful outside of `innernet` and don’t (yet) exist to my knowledge in the Rust community. I’ve reserved the crate names `wgctl` and `wgctl-sys` On crates.io and will happily transfer them if you’d like. I think the only issue I see with them being in the `innernet` mono-repo is versioning them along side `innernet` wouldn’t make too much sense if they were standalone for use in the greater Rust community.

**Comment by mcginty** [comment]
Yeah! Those crates are actually forked from https://crates.io/crates/wgctrl-rs and heavily modified, which reminds me to submit an upstream merge request on their GitLab.

If they want to take that change, then that's great, and if not then I am happy to release them as separate crates (although `wgctl` might be a bit too similarly named for a fork ;P)

**Comment by kbknapp** [comment]
Yeah I just noticed the missing `r` :man_facepalming: All my searching was for `ctl` (I guess being so used to the systemd naming my brain short circuited reading). 

For this issue then, yeah I agree perhaps a different name is more appropriate.

**Comment by mcginty** [comment]
MR submitted on their GitLab: https://gitlab.com/K900/wgctrl-rs/-/merge_requests/1

**Comment by mcginty** [comment]
Closed the GitLab MR and publishing our WireGuard control library at https://crates.io/crates/wireguard-control.

Thanks @kbknapp for opening the issue!
