### ISSUE TITLE
A very odd behavior if question is asked in non-interactive session

### ISSUE THREAD

**Issue by amarao** [tonarino/innernet#98]
I found that if `innernet-server add-cidr` is run by Ansible (via `command`) module it causes hang for playbook (as innernet-server is asking question). Moreover, it causes python on target module to hog 100% CPU at reading again and again output from stdout (which is refilled again and again).

I think innernet should detect if it's run in a non-interactive mode and to fail with an appropriate message if some questions are not provided via command line. It's better to have a definitive error than a runaway Turing machine in the infinite loop. Two of them, actually.

**Comment by kbknapp** [comment]
(Not the owner of  `innernet`, just a contributor)

One way to do this is to test if `stdout` is a TTY. Which can be done with the `libc` crate via [`isatty`](https://docs.rs/libc/0.2.95/libc/fn.isatty.html), or in a cross platform manner with the [`atty`](https://docs.rs/crate/atty/0.2.14) crate.

**Comment by mcginty** [comment]
I had assumed that the `dialoguer` crate would have failed if there was no TTY connected, but it doesn't check! Thanks for the issue @amarao.

I added a check using the `atty` crate since it was already a sub-dependency for us.
