### ISSUE TITLE
no tools for idempotent cidr management

### ISSUE THREAD

**Issue by amarao** [tonarino/innernet#99]
I work on Ansible automation for innernet-server (based on cli approach), and I found problems with cidr management.

To implement impotency I need to be able to see existing cidrs, or have some kind of reply of 'already existing' when adding existing cidr.

* there is no `list-cidrs`, `show-cidr` or something like this.
* Attempt to add the same cidr second time yields a confusing message:
```
WARN  innernet_server::db::cidr > tried to add a CIDR at the incorrect place in the tree (should be added to users).
Error: InvalidQuery
```

Just in case, steps to reproduce:

```
/usr/bin/innernet-server add-cidr --yes --cidr fdd3:f79c:981c:3333::/64 --name monitoring testnet --parent testnet
/usr/bin/innernet-server add-cidr --yes --cidr fdd3:f79c:981c:3333::/64 --name monitoring testnet --parent testnet
```
First line works fine, second cause error.

**Comment by mcginty** [comment]
Added `inn list-cidrs [--tree]` that will be available starting in v1.4.0-beta.2, thanks for opening the issue and your patience!
